"""Built-in names and how their libraries spell them.

The table is generated by tools/build_names.py from pyVBAanalysis's vendored
object models (VBA runtime, Excel, Word, PowerPoint, Access). It is loaded
on first use.
"""

from __future__ import annotations

import gzip
import json
from functools import lru_cache
from importlib import resources
from typing import Any

__all__ = ["HOSTS", "builtin_names", "library_names", "member_names", "table_source"]

HOSTS = ("excel", "word", "powerpoint", "access")


@lru_cache(maxsize=1)
def _table() -> dict[str, Any]:
    data = resources.files("pyprettyvba").joinpath("data").joinpath("names.json.gz").read_bytes()
    loaded: dict[str, Any] = json.loads(gzip.decompress(data).decode("utf-8"))
    return loaded


@lru_cache(maxsize=16)
def builtin_names(hosts: tuple[str, ...]) -> dict[str, str]:
    """Lower-case name -> spelling, for the VBA library and ``hosts``.

    The VBA library wins over a host where both name something, and hosts
    earlier in ``hosts`` win over later ones.
    """
    table = _table()
    names: dict[str, str] = {}
    sources: list[list[str]] = [table["vba"], table["compiler"]]
    for host in hosts:
        sources.append(table["hosts"].get(host, []))
    for source in sources:
        for name in source:
            names.setdefault(name.lower(), name)
    return names


@lru_cache(maxsize=16)
def library_names(hosts: tuple[str, ...]) -> dict[str, str]:
    """Every name the VBA library and ``hosts`` define, lower-case -> spelling.

    Functions, constants, types, enums and every member of every type: the
    names the VBE's project name table holds for a project that references
    these libraries, which it uses to spell any name no declaration spells,
    member names included. The VBA library comes first, then each host in
    order, and within a host its own library before Office's. A name one
    library spells two ways maps to "": nothing says which the VBE uses.
    """
    table = _table()
    names: dict[str, str] = {}
    sources: list[dict[str, str]] = [table["library"]["vba"], {c.lower(): c for c in table["compiler"]}]
    for host in hosts:
        sources.append(table["library"].get(host, {}))
    for source in sources:
        for key, spelling in source.items():
            names.setdefault(key, spelling)
    return names


@lru_cache(maxsize=16)
def member_names(object_name: str) -> dict[str, str]:
    """Names reachable after `object_name.`, lower-case -> spelling.

    The members of the VBA library objects `Debug` and `Err`, and for a
    library name (`VBA.Left$`, `Excel.Range`) that library's own names.
    """
    lower = object_name.lower()
    if lower == "vba":
        return builtin_names(())
    if lower in HOSTS:
        return {name.lower(): name for name in _table()["hosts"][lower]}
    members = _table()["members"].get(lower, [])
    return {name.lower(): name for name in members}


def table_source() -> dict[str, str]:
    """Where the table came from: pyVBAanalysis version and XLIDE commit."""
    source: dict[str, str] = _table()["source"]
    return source
