"""Write docs/rules.md from the rules themselves.

Every rule's summary, description, options, defaults and presets come from
the code, so the reference cannot drift from what the rules do. The unit
suite checks the file is current (tests/test_docs.py).

    python tools/build_docs.py
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from pyprettyvba import PRESETS, RULES  # noqa: E402
from pyprettyvba.config import _preset_rules  # noqa: E402
from pyprettyvba.rules.base import Rule  # noqa: E402

OUT = REPO / "docs" / "rules.md"
FIXTURES = REPO / "tests" / "fixtures" / "rules"


def _toml(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_toml(item) for item in value) + "]"
    return str(value)


def _cell(text: str) -> str:
    """Text for a Markdown table cell: `|` would end the cell."""
    return text.replace("|", "\\|")


def _presets_enabling(code: str) -> list[str]:
    return [preset for preset in PRESETS if _preset_rules(preset).get(code) is not None]


def _description(rule: type[Rule]) -> str:
    # Docstrings mark Python names ``like this``; Markdown wants one backtick.
    return inspect.cleandoc(rule.__doc__ or "").replace("``", "`")


def _rule_section(rule: type[Rule]) -> list[str]:
    lines = [f"## {rule.code}", "", _description(rule), ""]
    presets = _presets_enabling(rule.code)
    facts = [
        f"Category: {rule.category}.",
        "On by default." if rule.default_enabled else "Off by default.",
        f"Presets that enable it: {', '.join(presets) if presets else 'none'}.",
        "Fixes what it finds." if rule.fixable else "Reports only; it changes nothing.",
    ]
    if rule.vbe_canonical:
        facts.append("Part of what the VBE itself does to code it reads in (the `vbe` preset).")
    lines.extend(f"- {fact}" for fact in facts)
    lines.append("")
    if rule.options:
        lines += ["| Option | Default | Values | What it does |", "| --- | --- | --- | --- |"]
        for option in rule.options:
            if option.choices is not None:
                values = ", ".join(_toml(c) for c in option.choices)
            elif isinstance(option.default, bool):
                values = "true, false"
            elif option.minimum is not None and option.maximum is not None:
                values = f"integer, {option.minimum} to {option.maximum}"
            elif option.minimum is not None:
                values = f"integer, at least {option.minimum}"
            elif option.maximum is not None:
                values = f"integer, at most {option.maximum}"
            else:
                values = type(option.default).__name__
            doc = _cell(" ".join(option.doc.split()))
            default = _cell(_toml(option.default))
            lines.append(f"| `{option.name}` | `{default}` | {values} | {doc} |")
        lines.append("")
    cases = sorted(p.name for p in (FIXTURES / rule.code).iterdir()) if (FIXTURES / rule.code).is_dir() else []
    if cases:
        links = ", ".join(f"[{name}](../tests/fixtures/rules/{rule.code}/{name}/)" for name in cases)
        lines += [f"Examples: {links}.", ""]
    return lines


def render() -> str:
    lines = [
        "# Rules",
        "",
        "Generated by `tools/build_docs.py` from the rules themselves. Do not edit",
        "this file by hand; change the rule and run the tool.",
        "",
        "The rules run in the order below, each on the text the rules before it",
        "produced, and the whole pipeline repeats until nothing changes. Every",
        "rule can be enabled, disabled and configured in a `[rules]` table (see",
        "[configuration](configuration.md)) and suppressed with a",
        "`'@prettyvba-ignore` comment (see [suppression](suppression.md)).",
        "",
        "| Rule | What it does | Default | Fixes |",
        "| --- | --- | --- | --- |",
    ]
    for rule in RULES:
        default = "on" if rule.default_enabled else "off"
        fixes = "yes" if rule.fixable else "reports"
        lines.append(f"| [{rule.code}](#{rule.code}) | {rule.summary} | {default} | {fixes} |")
    lines.append("")
    for rule in RULES:
        lines += _rule_section(rule)
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
